language: julia

os:
  - linux

julia:
  - 1.6

env:
    global:
    - PYTHON=conda

after_success:
  - julia --inline=no -e 'using Pkg; Pkg.add("Coverage"); import QuantumLattices; joinpath(dirname(pathof(QuantumLattices))); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'using Pkg; Pkg.add("DocumenterTools"); Pkg.add("Documenter"); Pkg.add("SymPy"); Pkg.add(Pkg.PackageSpec(;name="BenchmarkTools", version="1.0.0")); ENV["DOCUMENTER_DEBUG"] = "true"; import QuantumLattices; joinpath(dirname(pathof(QuantumLattices))); include(joinpath("docs","make.jl"))'
