function id end
function value end
function dimension end
function ⊕ end
function ⊗ end
function add! end
function sub! end
function div! end
function expand end
function expand! end
function decompose end
function decompose! end
function permute end
function dtype end
function kind end
function update end
function update! end
function reset! end