name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.update(); Pkg.add("QuantumLattices"); Pkg.add("DocumenterTools"); Pkg.add("Documenter"); Pkg.add("SymPy"); Pkg.add(Pkg.PackageSpec(;name="BenchmarkTools", version="1.0.0")); ENV["DOCUMENTER_DEBUG"] = "true"; import QuantumLattices; joinpath(dirname(pathof(QuantumLattices))); include(joinpath("docs","make.jl"))'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl